# Generated by Django 6.0.3 on 2026-03-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_property_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New Construction'), ('renovated', 'Renovated'), ('good', 'Good Condition'), ('needs_work', 'Needs Work')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
